/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layouts/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    BookingItem: typeof import('./src/components/Dashboard/BookingItem.vue')['default']
    BookingModal: typeof import('./src/components/Modals/BookingModal.vue')['default']
    BuildingIcon: typeof import('./src/components/Icons/BuildingIcon.vue')['default']
    CalendarIcon: typeof import('./src/components/Icons/CalendarIcon.vue')['default']
    CameraIcon: typeof import('./src/components/Icons/CameraIcon.vue')['default']
    ClientModal: typeof import('./src/components/Modals/ClientModal.vue')['default']
    DesktopLayout: typeof import('./src/components/Layouts/DesktopLayout.vue')['default']
    DotsVerticalIcon: typeof import('./src/components/Icons/DotsVerticalIcon.vue')['default']
    HomeIcon: typeof import('./src/components/Icons/HomeIcon.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    MailIcon: typeof import('./src/components/Icons/MailIcon.vue')['default']
    PackageIcon: typeof import('./src/components/Icons/PackageIcon.vue')['default']
    PackageServiceModal: typeof import('./src/components/Modals/PackageServiceModal.vue')['default']
    PhoneIcon: typeof import('./src/components/Icons/PhoneIcon.vue')['default']
    PhotographerModal: typeof import('./src/components/Modals/PhotographerModal.vue')['default']
    PlusIcon: typeof import('./src/components/Icons/PlusIcon.vue')['default']
    QuickActionButton: typeof import('./src/components/Dashboard/QuickActionButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/Icons/SearchIcon.vue')['default']
    SidebarLink: typeof import('./src/components/Layouts/SidebarLink.vue')['default']
    StarIcon: typeof import('./src/components/Icons/StarIcon.vue')['default']
    StatsCard: typeof import('./src/components/Dashboard/StatsCard.vue')['default']
    StudioModal: typeof import('./src/components/Modals/StudioModal.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
    UsersIcon: typeof import('./src/components/Icons/UsersIcon.vue')['default']
    XIcon: typeof import('./src/components/Icons/XIcon.vue')['default']
  }
}
